# Generated by Django 6.0.2 on 2026-03-02 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_restaurant_owner'),
        ('bookings', '0005_remove_restaurant_address_alter_restaurant_owner'),
    ]

    operations = [
    ]
